### ISSUE TITLE
Add i18n

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/UriDereferencer#3]
If they are able, the services should return markup in the URI value's language, falling back on the locale of the site or installation. This will require services to accept a `lang` argument in `getResourceUrl()` and `getMarkup()`.

**Comment by jimsafley** [comment]
It occurs to me that Omeka has no option to tag URI values with a language, so this issue will remain unresolved until that becomes possible.

**Comment by allanaaa** [comment]
It does now @jimsafley!
