### ISSUE TITLE
Possibility for hooking into providers with API keys?

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/UriDereferencer#5]
Both DPLA and Europeana require an API key to query their endpoints. Would it be possible to add an interface for processing those keys?

https://pro.dp.la/developers/api-codex

https://pro.europeana.eu/resources/apis/search

**Comment by jimsafley** [comment]
On top of whatever interface is needed, it'll require adding a mechanism to inject options into services at runtime. It's unfortunate that DPLA and Europeana don't provide representations more freely.
